const dummyData = [
  {
    id: 1,
    productTitle: "Product 1",
    description: "This is a sample description for Product 1.",
    productType: "Furniture",
    companyName: "Company A",
    costPerMonth: 18.74,
    expiryDate: "2023-09-01",
    manufactureDate: "2023-06-03",
    productCode: "XYZ-1001",
    totalStock: 171,
  },
  {
    id: 2,
    productTitle: "Product 2",
    description: "This is a sample description for Product 2.",
    productType: "Toys",
    companyName: "Company B",
    costPerMonth: 50.24,
    expiryDate: "2023-07-10",
    manufactureDate: "2023-10-17",
    productCode: "XYZ-1002",
    totalStock: 345,
  },
  {
    id: 3,
    productTitle: "Product 3",
    description: "This is a sample description for Product 3.",
    productType: "Electronics",
    companyName: "Company C",
    costPerMonth: 24.57,
    expiryDate: "2023-09-01",
    manufactureDate: "2023-07-28",
    productCode: "XYZ-1003",
    totalStock: 175,
  },
  {
    id: 4,
    productTitle: "Product 4",
    description: "This is a sample description for Product 4.",
    productType: "Furniture",
    companyName: "Company D",
    costPerMonth: 79.55,
    expiryDate: "2023-11-08",
    manufactureDate: "2023-08-09",
    productCode: "XYZ-1004",
    totalStock: 55,
  },
  {
    id: 5,
    productTitle: "Product 5",
    description: "This is a sample description for Product 5.",
    productType: "Toys",
    companyName: "Company E",
    costPerMonth: 92.51,
    expiryDate: "2023-12-02",
    manufactureDate: "2023-07-07",
    productCode: "XYZ-1005",
    totalStock: 328,
  },
];

export default dummyData;
