export const links = {
  dashboard: { name: "Dashboard", href: "/dashboard" },
  startSell: { name: "Start Sell", href: "/sells" },
  orderReport: { name: "Order Report", href: "/report" },
  // productReport: { name: "Product Report", href: "/product-report" },
  productReport: { name: "Product Report", href: "/dashboard" },
  addCompany: { name: "Add Company", href: "/dashboard" },
  // addCompany: { name: "Add Company", href: "/add-company" },
  companyReport: { name: "Company Report", href: "/companies" },
  // addCategory: { name: "Add Category", href: "/add-category" },
  addCategory: { name: "Add Category", href: "/dashboard" },
  logout: { name: "Logout", href: "/dashboard" },
  // logout: { name: "Logout", href: "/logout" },
  addMedicine: { name: "Add Medicine", href: "/medicine" },
};
