spring:
  datasource:
    url: jdbc:mysql://localhost:3306/medease
    username: root
    password: MMpp@1973

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /api

  port: 8080

logging:
  level:
    root: warn
    com.chapp.med_ease: debug
    org.springframework.security: debug

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days